version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
    networks:
      - app-network

  client:
    build: ./Client
    restart: unless-stopped
    expose:
      - "80"  # Solo expuesto internamente
    networks:
      - app-network
   
  server:
    build: ./Server
    expose:
      - "3000"  # Solo expuesto internamente
    env_file: .env
    environment:
      - NODE_ENV=development
      - DB_URL=${DB_URL}
      - PORT=3000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
