version: "3.8"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Client/build:/usr/share/nginx/html  # Asumiendo que usas React/Vue
    depends_on:
      - server
      - client
    networks:
      - app-network

  client:
    build: 
      context: ./Client
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network
    # En tu Dockerfile del cliente asegúrate de construir la app
    # Ejemplo para React: RUN npm run build
   
  server:
    build: ./Server
    expose:
      - "3000"
    env_file: .env
    environment:
      - NODE_ENV=development
      - DB_URL=${DB_URL}
      - PORT=3000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
